{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.121.762.0 (23.09)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Calendar\",\"Customer\",\"Employee\",\"Food Inventory\",\"Sales\",\"Product\",\"Store\",\"_Measures\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Facts"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Dimensions"
      }
    ],
    "relationships": [
      {
        "name": "8a01ce91-484f-4f23-9714-5b8ee4be3890",
        "fromColumn": "transaction_date",
        "fromTable": "Sales",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "a66d0754-2ec9-4d1f-ad82-06b43b85754c",
        "fromColumn": "customer_id",
        "fromTable": "Sales",
        "toColumn": "customer_id",
        "toTable": "Customer"
      },
      {
        "name": "ead0a49a-8a5b-4879-a4e5-3598c81a3315",
        "fromColumn": "staff_id",
        "fromTable": "Sales",
        "toColumn": "staff_id",
        "toTable": "Employee"
      },
      {
        "name": "64e64e8e-1c77-4912-99a1-ca388cd57998",
        "fromColumn": "product_id",
        "fromTable": "Sales",
        "toColumn": "product_id",
        "toTable": "Product"
      },
      {
        "name": "f6cfe0a5-4434-434c-9bd2-6cd8c4655c11",
        "fromColumn": "store_id",
        "fromTable": "Food Inventory",
        "toColumn": "store_id",
        "toTable": "Store"
      },
      {
        "name": "8fc974c2-f272-43e9-a908-a531ac5a7c61",
        "fromColumn": "product_id",
        "fromTable": "Food Inventory",
        "toColumn": "product_id",
        "toTable": "Product"
      },
      {
        "name": "9267c2c2-2812-43bc-b5d8-5009c4dc9ba2",
        "fromColumn": "transaction_date",
        "fromTable": "Food Inventory",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "f891d9f0-dd98-4c5e-94a5-7341cddb4f9b",
        "fromColumn": "store_id",
        "fromTable": "Sales",
        "toColumn": "store_id",
        "toTable": "Store"
      },
      {
        "name": "21fc2192-6ee1-4994-a9e1-fa6535ac7a75",
        "fromColumn": "baked_date",
        "fromTable": "Food Inventory",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "1d868383-6eb0-49b1-a1a0-59adb6c740a3",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eef8adad-a386-4cd9-a0ef-c200e7aa9997",
            "sourceColumn": "Date_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Week_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b0844792-37ea-4398-90c1-41a822ff6be5",
            "sourceColumn": "Week_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Week_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "189ab0b1-76ea-41b1-9fdc-f0b893565c4a",
            "sourceColumn": "Week_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Month_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "878d7137-0750-4149-885f-08ad1aa171f1",
            "sourceColumn": "Month_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Month_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b821a0a-802a-491a-9ecd-edc59f053769",
            "sourceColumn": "Month_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7773a992-459d-4077-9e7b-1f2807b50970",
            "sourceColumn": "Quarter_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35cc98db-5786-4f1b-bded-da59723f81ce",
            "sourceColumn": "Quarter_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Year_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d85ca876-3b6d-4ae1-a250-ccd719729889",
            "sourceColumn": "Year_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Week_Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa3479fc-c2f4-4f9a-bff9-3a76efbb047b",
            "sourceColumn": "Week_Year",
            "summarizeBy": "none"
          },
          {
            "name": "Year_Half",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    SWITCH(",
              "        TRUE(),",
              "        MONTH('Calendar'[Date]) < 7, \"1H\",",
              "        MONTH('Calendar'[Date]) >= 7, \"2H\",",
              "        \"-\"",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "1ecb7d60-c6e1-4ee9-981b-cc2b93d740e3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year_Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    VAR __Q1 = 'Calendar'[Month_ID] IN {1,2,3}",
              "    VAR __Q2 = 'Calendar'[Month_ID] IN {4,5,6}",
              "    VAR __Q3 = 'Calendar'[Month_ID] IN {7,8,9}",
              "    VAR __Q4 = 'Calendar'[Month_ID] IN {10,11,12}",
              "",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        __Q1,\"Q1\" & \"-\" & 'Calendar'[Year_ID],",
              "        __Q2,\"Q2\" & \"-\" & 'Calendar'[Year_ID],",
              "        __Q3,\"Q3\" & \"-\" & 'Calendar'[Year_ID],",
              "        __Q4,\"Q4\" & \"-\" & 'Calendar'[Year_ID],",
              "        \"-\"",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "fcc484bb-25b2-4eea-994c-de35463e7d50",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "69d7ae7c-e3b5-48da-86b7-6a1f4bdbe428",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\DANE\\Power BI\\Maven Advanced DAX\\Advanced DAX Data Files\\Calendar.csv\"),[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Transaction_Date\", type date}, {\"Date_ID\", Int64.Type}, {\"Week_ID\", Int64.Type}, {\"Week_Desc\", type text}, {\"Month_ID\", Int64.Type}, {\"Month_Name\", type text}, {\"Quarter_ID\", Int64.Type}, {\"Quarter_Name\", type text}, {\"Year_ID\", Int64.Type}, {\"Week_Year\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Transaction_Date\", \"Date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1cca6503-f65b-4586-ab47-d22e52d08294",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "home_store",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d90d8ff-d206-4b60-9ecc-60c8b858f4e0",
            "sourceColumn": "home_store",
            "summarizeBy": "none"
          },
          {
            "name": "customer_first-name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75cc25fe-1ab5-4e4b-a5e0-1473cb7f5cf7",
            "sourceColumn": "customer_first-name",
            "summarizeBy": "none"
          },
          {
            "name": "customer_email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "349b5e6c-c4be-4a7e-aaa2-3677dfbecc97",
            "sourceColumn": "customer_email",
            "summarizeBy": "none"
          },
          {
            "name": "customer_since",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "af38c9e0-ff72-400a-87c5-d097039cb44d",
            "sourceColumn": "customer_since",
            "summarizeBy": "none"
          },
          {
            "name": "loyalty_card_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a30ca49e-d74f-4568-9c60-9a62ab1a5081",
            "sourceColumn": "loyalty_card_number",
            "summarizeBy": "none"
          },
          {
            "name": "birthdate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "147eb675-9e8a-492f-8ad2-7ee6eab0abb5",
            "sourceColumn": "birthdate",
            "summarizeBy": "none"
          },
          {
            "name": "gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a9958eb-270f-4880-8a48-bf1c1ac41d7f",
            "sourceColumn": "gender",
            "summarizeBy": "none"
          },
          {
            "name": "birth_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d4dba242-1a03-403a-9139-11b3cf59170b",
            "sourceColumn": "birth_year",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "FLOOR(",
              "    DIVIDE(",
              "        DATEDIFF(",
              "            Customer[birthdate],",
              "            TODAY(),",
              "            DAY",
              "        ),",
              "        365,25",
              "    ),",
              "    1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b7b9a299-96bc-4370-8adc-8ccbd2557fa7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sales (High/Low)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    VAR __TotalSales =",
              "        SUMX(",
              "            Sales,Sales[quantity_sold] * Sales[unit_price]",
              "        )",
              "    VAR __AllCustCnt = ",
              "        COUNTROWS(Customer)",
              "    VAR __AvgSales =",
              "        DIVIDE(",
              "            __TotalSales,__AllCustCnt",
              "        )",
              "    VAR __SalesCust =",
              "        SUMX(",
              "            RELATEDTABLE(Sales),    -- force filter context, the same as calculate",
              "            Sales[quantity_sold] * Sales[unit_price]",
              "        )",
              "    RETURN",
              "        IF(__SalesCust > __AvgSales, \"High\",\"Low\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e05f4624-8800-4f57-b0dc-e07d9387a3bf",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f12e2c4a-7c1a-4463-803e-78541e0cb4b0",
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\DANE\\Power BI\\Maven Advanced DAX\\Advanced DAX Data Files\\Customer Lookup.csv\"),[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_id\", Int64.Type}, {\"home_store\", Int64.Type}, {\"customer_first-name\", type text}, {\"customer_email\", type text}, {\"customer_since\", type date}, {\"loyalty_card_number\", type text}, {\"birthdate\", type date}, {\"gender\", type text}, {\"birth_year\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Employee",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "staff_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a2e1704c-e52e-482a-9cb2-e5f589df2949",
            "sourceColumn": "staff_id",
            "summarizeBy": "none"
          },
          {
            "name": "first_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7652e2d5-e78e-4f4e-8007-08a9ad96f6d5",
            "sourceColumn": "first_name",
            "summarizeBy": "none"
          },
          {
            "name": "last_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e01c4d08-fa53-4659-b2e1-2deff1c662c7",
            "sourceColumn": "last_name",
            "summarizeBy": "none"
          },
          {
            "name": "position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d592b24f-4fe0-47fd-ba1c-02678b44d83d",
            "sourceColumn": "position",
            "summarizeBy": "none"
          },
          {
            "name": "start_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "aa6f63ea-03b4-4d8a-ab35-85694c5d448d",
            "sourceColumn": "start_date",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbe881fb-1111-4b09-ac0a-351030eda8f3",
            "sourceColumn": "location",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1b59adbf-a46c-4cf5-973a-46217ad33420",
        "partitions": [
          {
            "name": "Employee",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\DANE\\Power BI\\Maven Advanced DAX\\Advanced DAX Data Files\\Employee Lookup.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"staff_id\", Int64.Type}, {\"first_name\", type text}, {\"last_name\", type text}, {\"position\", type text}, {\"start_date\", type date}, {\"location\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Food Inventory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52b5ea6b-1774-4b79-a803-967d7212b762",
            "sourceColumn": "store_id",
            "summarizeBy": "none"
          },
          {
            "name": "baked_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "02cc0d4a-02c3-498e-99ca-a40214dac47e",
            "sourceColumn": "baked_date",
            "summarizeBy": "none"
          },
          {
            "name": "transaction_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7fd3b248-3385-4397-8573-8b95521253e7",
            "sourceColumn": "transaction_date",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb892f08-f5a8-42f6-a8dc-a4ee9c1c664a",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "quantity_start_of_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e582abc4-9fca-4a7d-8d75-674b0924da4a",
            "sourceColumn": "quantity_start_of_day",
            "summarizeBy": "sum"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c1fd581b-65b9-4be7-8644-f34480c1723b",
            "sourceColumn": "quantity_sold",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d9409ce1-cd1d-4313-b87d-e13fb9b75c2d",
        "partitions": [
          {
            "name": "Food Inventory",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\DANE\\Power BI\\Maven Advanced DAX\\Advanced DAX Data Files\\Food Inventory.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"store_id\", Int64.Type}, {\"baked_date\", type date}, {\"transaction_date\", type date}, {\"product_id\", Int64.Type}, {\"quantity_start_of_day\", Int64.Type}, {\"quantity_sold\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "transaction_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "22eb71c9-e56c-4e38-a81f-39ecbb686b45",
            "sourceColumn": "transaction_id",
            "summarizeBy": "sum"
          },
          {
            "name": "transaction_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "60036c05-23a8-412b-83bb-888eced0213f",
            "sourceColumn": "transaction_date",
            "summarizeBy": "none"
          },
          {
            "name": "transaction_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "4a323534-bdfa-45d3-b0b4-e859f20eacde",
            "sourceColumn": "transaction_time",
            "summarizeBy": "none"
          },
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3a38a5d8-f784-40d5-87fe-c52bafb0e48f",
            "sourceColumn": "store_id",
            "summarizeBy": "none"
          },
          {
            "name": "staff_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5826b18b-24e1-4bb1-8493-bde6b8f87e94",
            "sourceColumn": "staff_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e60820e3-e3d5-41d8-846c-d4b74de3f718",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "instore_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "213f756f-34d4-46ad-900d-f8ce4daca33d",
            "sourceColumn": "instore_yn",
            "summarizeBy": "none"
          },
          {
            "name": "order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5d6062b0-9504-407c-9941-9e7f5cc965a4",
            "sourceColumn": "order",
            "summarizeBy": "sum"
          },
          {
            "name": "line_item_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8602fa80-106d-4d7e-bf83-ab46599c008d",
            "sourceColumn": "line_item_id",
            "summarizeBy": "sum"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5cc96ad4-223a-4c5e-95d7-f67932f615de",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "898b7ea5-6716-4d17-965b-a1695ade6de6",
            "sourceColumn": "quantity_sold",
            "summarizeBy": "sum"
          },
          {
            "name": "unit_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0a272b5a-d8cc-4079-83b6-8c0605208509",
            "sourceColumn": "unit_price",
            "summarizeBy": "sum"
          },
          {
            "name": "promo_item_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d7ec782-acd0-4b2f-b735-b95416fe68a1",
            "sourceColumn": "promo_item_yn",
            "summarizeBy": "none"
          },
          {
            "name": "Time Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "    FLOOR(",
              "        Sales[transaction_time],",
              "        \"1:00\"",
              "    )"
            ],
            "formatString": "Long Time",
            "lineageTag": "23a8ae9a-8ea6-4be3-b67a-0230e3996a9d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Transaction Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    FORMAT(Sales[transaction_date],\"yyyy-mm-dd\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "07b0bd52-cb92-4368-8d9c-dc108eee7f91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Product Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Product'[product_group])",
            "isDataTypeInferred": true,
            "lineageTag": "cdd00542-3aa1-4a8c-94cd-178d3c08f6c1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f3f15483-f945-4e80-b812-87c5d5503a18",
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\DANE\\Power BI\\Maven Advanced DAX\\Advanced DAX Data Files\\Sales by Store.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"transaction_date\", type date}, {\"transaction_time\", type time}, {\"store_id\", Int64.Type}, {\"staff_id\", Int64.Type}, {\"customer_id\", Int64.Type}, {\"instore_yn\", type text}, {\"order\", Int64.Type}, {\"line_item_id\", Int64.Type}, {\"product_id\", Int64.Type}, {\"quantity_sold\", Int64.Type}, {\"unit_price\", type number}, {\"promo_item_yn\", type text}, {\"transaction_id\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7eb03924-3b90-48f7-94b0-12497eaf8348",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "effad7e7-1e4d-46d6-b1bd-e2bb1f970892",
            "sourceColumn": "product_group",
            "summarizeBy": "none"
          },
          {
            "name": "product_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d99e6f64-13ae-4b8b-8f43-35d3c71e3f96",
            "sourceColumn": "product_category",
            "summarizeBy": "none"
          },
          {
            "name": "product_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6a36bf0-33d5-4150-b467-79418d6c33ed",
            "sourceColumn": "product_type",
            "summarizeBy": "none"
          },
          {
            "name": "product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60a82ad4-dc3f-4efc-9d56-ea0526df1ab6",
            "sourceColumn": "product",
            "summarizeBy": "none"
          },
          {
            "name": "product_description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f0de8f7-0d22-483a-99a6-cfb80955bce4",
            "sourceColumn": "product_description",
            "summarizeBy": "none"
          },
          {
            "name": "unit_of_measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00e3e5a8-d186-40dc-983f-d9aa4fa921a8",
            "sourceColumn": "unit_of_measure",
            "summarizeBy": "none"
          },
          {
            "name": "current_cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6ef00de1-1d7f-4f27-8d0c-5ca61ac1b650",
            "sourceColumn": "current_cost",
            "summarizeBy": "sum"
          },
          {
            "name": "current_wholesale_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1914a252-6a66-4147-bff7-cd2c31947ada",
            "sourceColumn": "current_wholesale_price",
            "summarizeBy": "sum"
          },
          {
            "name": "current_retail_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9dec67ef-384e-4570-b19a-2b762ee69d5d",
            "sourceColumn": "current_retail_price",
            "summarizeBy": "sum"
          },
          {
            "name": "tax_exempt_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d139255d-0296-4ecb-a53a-0a95236a2d01",
            "sourceColumn": "tax_exempt_yn",
            "summarizeBy": "none"
          },
          {
            "name": "promo_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "430e3c9a-4498-4f07-8e41-4be3d0a67c75",
            "sourceColumn": "promo_yn",
            "summarizeBy": "none"
          },
          {
            "name": "new_product_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dd761cb-bdd5-43ab-91b8-65088ce75fca",
            "sourceColumn": "new_product_yn",
            "summarizeBy": "none"
          },
          {
            "name": "Number of Food Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "    SUMX(",
              "        RELATEDTABLE('Food Inventory'),",
              "        'Food Inventory'[quantity_start_of_day]",
              "    )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9c3153c8-ab66-42ff-adf5-b923df97637f",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "de9f93b6-754d-49b5-a7d0-70b166c3e999",
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\DANE\\Power BI\\Maven Advanced DAX\\Advanced DAX Data Files\\Product Lookup (Updated).csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"product_id\", Int64.Type}, {\"product_group\", type text}, {\"product_category\", type text}, {\"product_type\", type text}, {\"product\", type text}, {\"product_description\", type text}, {\"unit_of_measure\", type text}, {\"current_cost\", type number}, {\"current_wholesale_price\", type number}, {\"current_retail_price\", type number}, {\"tax_exempt_yn\", type text}, {\"promo_yn\", type text}, {\"new_product_yn\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Store",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "36c850f5-700b-47c9-a302-1eaf4c68db89",
            "sourceColumn": "store_id",
            "summarizeBy": "none"
          },
          {
            "name": "store_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53cff48e-2c2a-4d84-8a12-80dba5177a79",
            "sourceColumn": "store_type",
            "summarizeBy": "none"
          },
          {
            "name": "store_square_feet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "13818081-6e37-4d39-9bdf-4aea35ede426",
            "sourceColumn": "store_square_feet",
            "summarizeBy": "sum"
          },
          {
            "name": "store_address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c62a0bf6-05dc-476d-a10f-afcdf2fe0deb",
            "sourceColumn": "store_address",
            "summarizeBy": "none"
          },
          {
            "name": "store_city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fad9af33-50d9-4339-b3ce-d73120be7d3c",
            "sourceColumn": "store_city",
            "summarizeBy": "none"
          },
          {
            "name": "store_state_province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bcdb79d-ff3b-4bff-9fe6-6fece1602604",
            "sourceColumn": "store_state_province",
            "summarizeBy": "none"
          },
          {
            "name": "store_postal_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4edace2f-2e87-432b-b397-e4ecbf51c636",
            "sourceColumn": "store_postal_code",
            "summarizeBy": "sum"
          },
          {
            "name": "store_longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "abe9e9d8-8d29-47c2-9f6f-4b3f8634f629",
            "sourceColumn": "store_longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "store_latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81b06f69-6a6d-4b7a-b3ab-756089527b39",
            "sourceColumn": "store_latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dbfb541d-2a92-4eb0-b5fe-ee6437d461c3",
            "sourceColumn": "manager",
            "summarizeBy": "sum"
          },
          {
            "name": "Neighorhood",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eabe898a-9017-4111-9529-7ea076a9b491",
            "sourceColumn": "Neighorhood",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d2f2f5a7-29fc-4b4b-9bb1-128c51044666",
        "partitions": [
          {
            "name": "Store",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\DANE\\Power BI\\Maven Advanced DAX\\Advanced DAX Data Files\\Store Lookup.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"store_id\", Int64.Type}, {\"store_type\", type text}, {\"store_square_feet\", Int64.Type}, {\"store_address\", type text}, {\"store_city\", type text}, {\"store_state_province\", type text}, {\"store_postal_code\", Int64.Type}, {\"store_longitude\", type number}, {\"store_latitude\", type number}, {\"manager\", Int64.Type}, {\"Neighorhood\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "000d0f68-5074-4152-875d-61848d76c3fa",
        "measures": [
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    SUMX(",
              "        Sales,",
              "        Sales[quantity_sold] * Sales[unit_price]",
              "    )"
            ],
            "lineageTag": "9cd8df06-c524-4130-bfdf-e628ccca2b73"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cost",
            "expression": [
              "",
              "        SUMX(",
              "            Sales,",
              "            Sales[quantity_sold] * ",
              "            RELATED(",
              "                'Product'[current_cost]",
              "            )",
              "        )",
              ""
            ],
            "lineageTag": "c06d1edb-9e0f-4d28-b0d1-9ffe6411e1bf"
          },
          {
            "name": "Profit",
            "displayFolder": "Sales",
            "expression": [
              "",
              "    COALESCE([Sales] - [Cost],\"-\")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "0601c8cc-7a83-44f5-a0f2-961a51a2e2fc"
          },
          {
            "name": "Orders by Females",
            "displayFolder": "Orders",
            "expression": [
              "",
              "    VAR __TotalOrdersFemale = ",
              "        CALCULATE(",
              "            SUM(",
              "                Sales[quantity_sold]",
              "            ),",
              "            FILTER(",
              "                Customer,",
              "                Customer[gender] = \"F\"",
              "            )",
              "        )",
              "RETURN",
              "    __TotalOrdersFemale"
            ],
            "formatString": "0",
            "lineageTag": "673c3ff2-e29a-4ba6-83ef-82b0cc375594"
          },
          {
            "name": "Customers #",
            "displayFolder": "Counts",
            "expression": [
              "",
              "    DISTINCTCOUNT(",
              "        Customer[customer_id]",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "f2b59d9a-264e-40cc-94c1-c2b7d6254d4e"
          },
          {
            "name": "Customers #2",
            "displayFolder": "Counts",
            "expression": [
              "",
              "    COUNTROWS(",
              "        VALUES(",
              "            Customer[customer_id]",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "f9b58718-7a32-44fa-a1e9-7b8594076f55"
          },
          {
            "name": "Employees #",
            "displayFolder": "Counts",
            "expression": [
              "",
              "    COUNTROWS(",
              "        Employee",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "11244ddd-57f8-4b25-bc1b-767b3382f77e"
          },
          {
            "name": "Cost Currency",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pl-PL\"}"
              }
            ],
            "displayFolder": "Cost",
            "expression": [
              "",
              "    ROUND(",
              "        CURRENCY(",
              "            [Cost]",
              "        ),2",
              "    )",
              ""
            ],
            "formatString": "#,0.###############\\ \"z\";-#,0.###############\\ \"z\";#,0.###############\\ \"z\"",
            "lineageTag": "b6788996-17fd-4fa9-ab09-182ab663e1c8"
          },
          {
            "name": "Sales PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    var __SalesPY =",
              "        CALCULATE(",
              "            [Sales],",
              "            DATEADD('Calendar'[Date],-1,YEAR)",
              "        )",
              "    var __Result =",
              "        COALESCE(__SalesPY,\"-\")",
              "",
              "    RETURN",
              "        __Result",
              "    "
            ],
            "lineageTag": "e31f3344-cf1d-40e2-945d-3ba41660e4eb"
          },
          {
            "name": "Store 3 Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],KEEPFILTERS(Store[store_id] = 3)",
              "    )"
            ],
            "lineageTag": "cf2a9f6f-1245-4eab-a1cb-092d655bdc33"
          },
          {
            "name": "Store 5 Profit",
            "displayFolder": "Profit",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Profit],",
              "        KEEPFILTERS(Store[store_id] = 5)",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "2d2464b3-c1c5-4321-8365-2ac8a6d6beb7"
          },
          {
            "name": "Store 5 Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],KEEPFILTERS(Store[store_id] = 5)",
              "    )"
            ],
            "lineageTag": "269f7262-caeb-4369-87dd-177ea8a5fa93"
          },
          {
            "name": "Store 8 Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],KEEPFILTERS(Store[store_id] = 8)",
              "    )"
            ],
            "lineageTag": "026b08f0-3d54-4984-a1f7-3e54bb236257"
          },
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],REMOVEFILTERS()",
              "    )"
            ],
            "lineageTag": "df86f91c-0586-4b0a-9d5c-58c1f1fc253a"
          },
          {
            "name": "Store 3 % Sales",
            "displayFolder": "Sales",
            "expression": [
              "",
              "    var __StoreNumber = 3",
              "    var __StoreSales = CALCULATE([Sales],KEEPFILTERS(Store[store_id]=__StoreNumber))",
              "    var __TotalSales = ",
              "        CALCULATE([Sales],REMOVEFILTERS())",
              "    var __Result = ",
              "        DIVIDE(__StoreSales,__TotalSales)",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bd78f203-9ed5-4b2c-a42b-690bd6cfb3aa"
          },
          {
            "name": "Store 5 % Sales",
            "displayFolder": "Sales",
            "expression": [
              "",
              "    var __StoreNumber = 5",
              "    var __StoreSales = CALCULATE([Sales],KEEPFILTERS(Store[store_id]=__StoreNumber))",
              "    var __TotalSales = ",
              "        CALCULATE([Sales],REMOVEFILTERS())",
              "    var __Result = ",
              "        DIVIDE(__StoreSales,__TotalSales)",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8f811fb6-c67e-4bf3-965d-6a982a7c088d"
          },
          {
            "name": "Store 8 % Sales",
            "displayFolder": "Sales",
            "expression": [
              "",
              "    var __StoreNumber = 8",
              "    var __StoreSales = CALCULATE([Sales],KEEPFILTERS(Store[store_id]=__StoreNumber))",
              "    var __TotalSales = ",
              "        CALCULATE([Sales],REMOVEFILTERS())",
              "    var __Result = ",
              "        DIVIDE(__StoreSales,__TotalSales)",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6861d5f3-e886-4feb-b623-68ec975805e0"
          },
          {
            "name": "Store 3 Sales 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],Store[store_id] = 3",
              "    )"
            ],
            "lineageTag": "a386d336-4ee4-4edb-8d78-553f362b33e9"
          },
          {
            "name": "% of Store Sales",
            "displayFolder": "Sales",
            "expression": [
              "",
              "    VAR __TotalSalesStores =",
              "        CALCULATE([Sales],REMOVEFILTERS(Store[store_id]))",
              "    VAR __TotalSalesGroups =",
              "        CALCULATE([Sales],REMOVEFILTERS('Product'[product_group]))",
              "    VAR __DivideStores =",
              "        DIVIDE([Sales],__TotalSalesStores)",
              "    VAR __DivideGroups =",
              "        DIVIDE([Sales],__TotalSalesGroups)",
              "    VAR __Result =",
              "        IF(",
              "            ISINSCOPE(Store[store_id]),__DivideStores,__DivideGroups",
              "        )",
              "    RETURN",
              "        __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec489a41-a707-45cb-b1a9-52d0681c1249"
          },
          {
            "name": "Sales Cumulative",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],",
              "        FILTER(",
              "            ALL('Calendar'[Date]),",
              "            'Calendar'[Date] <=  MAX('Calendar'[Date])",
              "        )",
              "    )"
            ],
            "lineageTag": "593a9f82-4681-4162-88b0-4b82927d5e84"
          },
          {
            "name": "Big Orders",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],FILTER(Sales,Sales[quantity_sold] > 3)",
              "    )"
            ],
            "lineageTag": "69fe81a6-9297-4c05-bef0-619562fed42b"
          },
          {
            "name": "Big Orders 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "var __tab = FILTER(Sales,Sales[quantity_sold] > 3)",
              "",
              "RETURN",
              "    CALCULATE(",
              "        [Sales],__tab",
              "    )"
            ],
            "lineageTag": "77fd2762-e9ea-41e5-98e6-c0a2413abda7"
          },
          {
            "name": "Sales (ALLEXCEPT)",
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],",
              "        ALLEXCEPT(",
              "            Sales,'Product'[product_group],'Calendar'[Date]",
              "        )",
              "",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "938b4253-5bd3-491d-b7a4-6094c15f6ce8"
          },
          {
            "name": "Sales (ALLEXCEPT 2)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],",
              "        ALLEXCEPT(Sales,Store[store_id],'Calendar'[Date],'Product'[product_group],Customer[customer_first-name])",
              "    )"
            ],
            "lineageTag": "20266bb4-e7fc-48aa-8d58-4831cbc39f8b"
          },
          {
            "name": "% of store-level sales",
            "expression": [
              "",
              "    var __StoreLevelSales =",
              "        CALCULATE(",
              "            [Sales],",
              "            REMOVEFILTERS('Customer'),",
              "            KEEPFILTERS('Calendar')",
              "        )",
              "    var __Ratio =",
              "        DIVIDE(",
              "            [Sales (ALLEXCEPT 2)],__StoreLevelSales",
              "        )",
              "    RETURN",
              "        __Ratio"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "b382f3b7-0893-4581-bb80-720f7b28f122"
          },
          {
            "name": "Selected Sales (ALLSELECTED)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Sales],",
              "        ALLSELECTED()",
              "    )"
            ],
            "lineageTag": "541df784-7d68-4fcd-aaef-701eb53f2f19"
          },
          {
            "name": "Total Sold",
            "displayFolder": "Food Inventory",
            "expression": [
              "",
              "    SUM('Food Inventory'[quantity_sold])"
            ],
            "formatString": "0",
            "lineageTag": "0f0633e7-a6b1-4e2a-9f21-be40092105fb"
          },
          {
            "name": "Total Baked",
            "displayFolder": "Food Inventory",
            "expression": [
              "",
              "    SUM('Food Inventory'[quantity_start_of_day])"
            ],
            "formatString": "0",
            "lineageTag": "6a724974-b511-4391-8f6a-1f78c3be6a14"
          },
          {
            "name": "% of Total Baked",
            "displayFolder": "Food Inventory",
            "expression": [
              "",
              "    var __AllBaked =",
              "        CALCULATE([Total Baked],ALLSELECTED())",
              "    VAR __Ratio =",
              "        DIVIDE(",
              "            [Total Baked],__AllBaked",
              "        )",
              "    RETURN ",
              "        __Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a78b9eac-57c5-441d-8574-0e5951d3a1f7"
          },
          {
            "name": "% of Total Sold",
            "displayFolder": "Food Inventory",
            "expression": [
              "",
              "    var __AllSold =",
              "        CALCULATE([Total Sold],ALLSELECTED())",
              "    VAR __Ratio =",
              "        DIVIDE(",
              "            [Total Sold],__AllSold",
              "        )",
              "    RETURN ",
              "        __Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e48e65d5-0ac6-43f5-80a2-43a3f9186059"
          },
          {
            "name": "Wholesale Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales",
            "expression": [
              "",
              "    SUMX(",
              "        Sales,",
              "        Sales[quantity_sold] * RELATED('Product'[current_cost])",
              "    )"
            ],
            "lineageTag": "f50a49f1-534c-406a-884f-408f131243b8"
          },
          {
            "name": "Quantity (USERELATIONSHIP)",
            "displayFolder": "Quantity",
            "expression": [
              "",
              "    CALCULATE(",
              "        SUM('Food Inventory'[quantity_sold]),",
              "        USERELATIONSHIP('Food Inventory'[baked_date],'Calendar'[Date])",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "02ca8055-870b-4956-a50b-48c2b728dea5"
          },
          {
            "name": "Number of Employees (CROSSFILTER)",
            "expression": [
              "",
              "    CALCULATE(COUNTROWS(Employee),",
              "    CROSSFILTER(Sales[staff_id],Employee[staff_id],Both)",
              "    )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "913f0222-9073-499d-9cce-88156a8c21bd"
          },
          {
            "name": "Customers who Purchased",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS(Customer),",
              "        CROSSFILTER(Sales[customer_id],Customer[customer_id],Both",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "bfed211f-2c87-48e2-bcfa-3bf5243d8384"
          },
          {
            "name": "Average Order Value (CWP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        [Sales],",
              "        [Customers who Purchased]",
              "    )"
            ],
            "lineageTag": "22306798-9ead-4163-9686-01e9b6aff79f"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Distinct Products",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a0d9b31475034db6b5525cd3d37a78c4"
          }
        ],
        "columns": [
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a40e181b-55a3-4ae7-87e9-3f741635f842",
            "sourceColumn": "Product[product_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2a3c0235-c60a-4166-bf80-0b19bb942497",
        "partitions": [
          {
            "name": "Distinct Products",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "    VALUES('Product'[product_id])"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ADDCOLUMNS Sample",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cfcc35db1c7f4eeda22d74f0817d5271"
          }
        ],
        "columns": [
          {
            "name": "transaction_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a66386e5-65fe-4510-a961-13234c37ca2d",
            "sourceColumn": "Sales[transaction_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "transaction_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6fc296f0-8c26-4676-acf5-fa40c7a4c2da",
            "sourceColumn": "Sales[transaction_date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "transaction_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e05d1df3-ceea-46a6-be49-7d17b82169b7",
            "sourceColumn": "Sales[transaction_time]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "04a8d9d3-b361-474b-893a-463af402787b",
            "sourceColumn": "Sales[store_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "staff_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b2fe911a-91d1-4405-9384-ebdf5aabfaee",
            "sourceColumn": "Sales[staff_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "897cd8fe-2151-42f5-bd93-5b94527e6fa4",
            "sourceColumn": "Sales[customer_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "instore_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "af91c90a-e7cd-4479-9884-f726b3322e50",
            "sourceColumn": "Sales[instore_yn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e5cd21a6-5f5e-4ffc-a98f-86f76ce025eb",
            "sourceColumn": "Sales[order]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "line_item_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5ab7c252-6e36-4d65-8fbd-3d680b33c170",
            "sourceColumn": "Sales[line_item_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0038a5b3-5b5f-4b0f-a9b8-e014ca1f441d",
            "sourceColumn": "Sales[product_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1345cbdf-e5b0-4659-9bdc-cd1b89b85e85",
            "sourceColumn": "Sales[quantity_sold]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "unit_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "336657b3-2f7e-4db7-8221-b0691c2830cd",
            "sourceColumn": "Sales[unit_price]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "promo_item_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5dfb5e09-389c-4ec1-8bbb-6e0d5b3eee04",
            "sourceColumn": "Sales[promo_item_yn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Time Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ed19e652-5d74-4442-8bd3-4b7393f5505a",
            "sourceColumn": "Sales[Time Group]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Transaction Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dd598ceb-c44f-4cfb-b86d-06f6cce2787b",
            "sourceColumn": "Sales[Transaction Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "@Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0ba7bed6-6705-408b-94d9-6863ad51ecd2",
            "sourceColumn": "[@Sales]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Product Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2d4c0490-f21e-4998-a9e9-b6d0dabeaf33",
            "sourceColumn": "Sales[Product Group]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6fff004f-d402-4209-ba93-7cb463c56fc7",
        "partitions": [
          {
            "name": "ADDCOLUMNS Sample",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    Sales,",
                "    \"@Sales\",[Sales]",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SELECTCOLUMNS Sample",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f4e8ddaa9b5040a5a8be5a672e3afa55"
          }
        ],
        "columns": [
          {
            "name": "@Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7532cd86-1766-4921-a161-c13114b9a8ac",
            "sourceColumn": "[@Sales]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5c5c7e14-9051-4443-b70f-5ce145d0251b",
        "partitions": [
          {
            "name": "SELECTCOLUMNS Sample",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SELECTCOLUMNS(",
                "    Sales,",
                "    \"@Sales\",[Sales]",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Unsold Pastries",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bb7daf4caf9d46d9a78b4e8896a779cc"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fd4e3ae1-5264-4f48-911a-f1f2dda22742",
            "sourceColumn": "Calendar[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "63694b70-87c0-4382-80c3-403789ca4c98",
            "sourceColumn": "Store[store_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "451d02d6-cf4c-4840-963a-6a7afe7ea8c8",
            "sourceColumn": "Food Inventory[quantity_sold]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "quantity_start_of_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "80590b31-80f6-449d-a66a-628a396d9432",
            "sourceColumn": "Food Inventory[quantity_start_of_day]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "current_retail_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "148b76e3-e33f-4352-939e-12d9bb6bdc9c",
            "sourceColumn": "Product[current_retail_price]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d6773881-eef1-4ffb-b007-93c9dfbcdb6b",
            "sourceColumn": "Product[product]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "75015817-7fc1-414e-b377-24e80daf4457",
        "measures": [
          {
            "name": "Food Sold",
            "expression": [
              "",
              "    SUM(",
              "        'Unsold Pastries'[quantity_sold]",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "13de27a0-0610-4ee6-9c7f-2b1a64ef2fdc"
          },
          {
            "name": "Food Unsold",
            "expression": [
              "",
              "    SUMX(",
              "        'Unsold Pastries',",
              "        'Unsold Pastries'[quantity_start_of_day] - 'Unsold Pastries'[quantity_sold]",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "9cdb9149-141a-4b3b-a841-07f8b56957b5"
          },
          {
            "name": "Lost Revenue",
            "expression": [
              "",
              "    SUMX(",
              "        'Unsold Pastries',",
              "        [Food Unsold] * 'Unsold Pastries'[current_retail_price]",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "804d3c76-df45-4e41-8f6b-8909aaa3d98f"
          },
          {
            "name": "Food Unsold 2",
            "expression": [
              "",
              "    SUMX(",
              "        'Food Inventory',",
              "        'Food Inventory'[quantity_start_of_day] - 'Food Inventory'[quantity_sold]",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "fda1ba8e-d4d8-4448-8d55-a4766259aed6"
          }
        ],
        "partitions": [
          {
            "name": "Unsold Pastries",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "    SUMMARIZE(",
                "        FILTER(",
                "            'Food Inventory',",
                "            'Food Inventory'[quantity_sold] <> 'Food Inventory'[quantity_start_of_day]",
                "        ),",
                "        'Calendar'[Date],",
                "        Store[store_id],",
                "        'Food Inventory'[quantity_sold],",
                "        'Food Inventory'[quantity_start_of_day],",
                "        'Product'[current_retail_price],",
                "        'Product'[product]",
                "    )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ROW Sample",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "31bff6f0879d4796a7a85a0cf6e03e67"
          }
        ],
        "columns": [
          {
            "name": "Customers Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "13d30acb-b8c0-49f6-8e29-fc2ccef2e851",
            "sourceColumn": "[Customers Sales]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0826f0d4-a386-45e7-b6ee-cb2b80c96062",
            "sourceColumn": "[Orders]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ae926486-9e5c-4285-8fc9-fe0920fee100",
        "partitions": [
          {
            "name": "ROW Sample",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "    ROW(",
                "        \"Customers Sales\", [Sales],",
                "        \"Orders\",",
                "        SUMX(",
                "            Sales,",
                "            Sales[quantity_sold]",
                "        )",
                "    )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Returning Customers",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "46cb6e792e1d4739b9180371d2cc76a7"
          }
        ],
        "columns": [
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5eaf00bb-b4c2-4915-b13f-b26f94ea26f9",
            "sourceColumn": "Sales[customer_id]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "eec31c83-6717-4d8a-a0fa-201321604b9f",
            "sourceColumn": "[Sales]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ec8082f8-f1be-401e-90e2-e463ae8f6c99",
            "sourceColumn": "[Profit]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "dcd9bb29-1e5b-47cb-9b20-639d07d77b5c",
        "partitions": [
          {
            "name": "Returning Customers",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "    var __week45 =",
                "    CALCULATETABLE(",
                "        VALUES(Sales[customer_id]),",
                "        'Calendar'[Week_ID] = 46,",
                "        'Calendar'[Year_ID] = 2018",
                "    )",
                "    var __week46 =",
                "    CALCULATETABLE(",
                "        VALUES(Sales[customer_id]),",
                "        'Calendar'[Week_ID] = 45,",
                "        'Calendar'[Year_ID] = 2018",
                "    )",
                "    var __ReturningCustomers =",
                "            INTERSECT(__week45,__week46)",
                "    ",
                "    var __ReturningValues = ",
                "        CALCULATETABLE(",
                "            ADDCOLUMNS(",
                "                __ReturningCustomers,",
                "                \"Sales\", [Sales],",
                "                \"Profit\", FORMAT([Profit],\"0.00\")",
                "            ), 'Calendar'[Week_ID] = 46",
                "        )",
                "",
                "    RETURN",
                "        __ReturningValues",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}